name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH Key to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan rafael.informaticamajada.es >> ~/.ssh/known_hosts

    - name: Deploy
      run: |
        ssh illian@rafael.informaticamajada.es << 'EOF'
          cd /var/www/html/LocalEvents-Front
          git pull origin development
          npm install
          npm run build
        EOF